# Generated by Django 5.2 on 2025-05-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('permissions_level', models.CharField(default='standard', max_length=50)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farming_experience_years', models.PositiveIntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_owned', models.TextField(blank=True, null=True)),
                ('preferred_crops', models.TextField(blank=True, null=True)),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='core.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='core.farmer'),
        ),
    ]
