# Generated by Django 5.2 on 2025-05-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admin_farmer_alter_farm_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedWeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('treatment_methods', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_type',
        ),
        migrations.AddField(
            model_name='farm',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='price_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='size_category',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_nitrogen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_phosphorus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_potassium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('area_planted_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_prediction_date', models.DateTimeField(blank=True, null=True)),
                ('yield_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_plantings', to='core.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_crops', to='core.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('YIELD', 'Yield Prediction'), ('FERTILIZER', 'Fertilizer Usage'), ('WATER', 'Water Usage'), ('CROP', 'Crop Suggestion'), ('WEATHER', 'Weather Forecast Info')], max_length=20)),
                ('details', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.farm')),
                ('farm_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.farmcrop')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('DISEASE', 'Disease Detection'), ('WEED', 'Weed Detection')], max_length=10)),
                ('image', models.ImageField(upload_to='scans/')),
                ('detection_results', models.JSONField(blank=True, null=True)),
                ('treatment_suggestion', models.TextField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('weed_coverage_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detected_weeds', models.ManyToManyField(blank=True, related_name='scans', to='core.detectedweed')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.farm')),
                ('farm_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.farmcrop')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('condition', models.CharField(choices=[('SUNNY', 'Sunny'), ('CLOUDY', 'Cloudy'), ('PARTLY_CLOUDY', 'Partly Cloudy'), ('RAINY', 'Rainy'), ('STORMY', 'Stormy'), ('SNOWY', 'Snowy'), ('FOGGY', 'Foggy'), ('WINDY', 'Windy')], max_length=20)),
                ('temperature_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecast_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='core.farm')),
            ],
            options={
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
