# Generated by Django 5.2 on 2025-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crop_detectedweed_remove_farm_farm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Clay', 'Clay'), ('Sandy', 'Sandy'), ('Loamy', 'Loamy'), ('Silty', 'Silty'), ('Peaty', 'Peaty'), ('Chalky', 'Chalky')], max_length=20, null=True),
        ),
    ]
