# Generated by Django 5.2 on 2025-05-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_farm_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farming_method',
            field=models.CharField(blank=True, choices=[('Organic', 'Organic Farming'), ('Conventional', 'Conventional Farming'), ('Mixed', 'Mixed Methods'), ('Permaculture', 'Permaculture'), ('Hydroponic', 'Hydroponic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='has_road_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='has_water_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip Irrigation'), ('Sprinkler', 'Sprinkler System'), ('Flood', 'Flood Irrigation'), ('Furrow', 'Furrow Irrigation'), ('None', 'No Irrigation')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='storage_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
