# Generated by Django 5.2 on 2025-05-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_farm_farming_method_farm_has_electricity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='expected_yield_per_hectare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='growth_stage',
            field=models.CharField(blank=True, choices=[('Planting', 'Planting'), ('Germination', 'Germination'), ('Vegetative', 'Vegetative Growth'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting'), ('Harvest', 'Harvest Ready'), ('Post-Harvest', 'Post-Harvest')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='health_status',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Critical', 'Critical')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='last_fertilized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='planting_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='projected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='watering_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Every_2_Days', 'Every 2 Days'), ('Every_3_Days', 'Every 3 Days'), ('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('As_Needed', 'As Needed')], max_length=20, null=True),
        ),
    ]
