# Generated by Django 5.2 on 2025-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_farmcrop_expected_yield_per_hectare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_progress',
            field=models.JSONField(blank=True, help_text='Stores temporary onboarding progress data', null=True),
        ),
    ]
