# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250510_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Tractor', 'Tractor'), ('Harvester', 'Harvester'), ('Seeder', 'Seeder'), ('Sprayer', 'Sprayer'), ('Trailer', 'Trailer'), ('Tillage', 'Tillage'), ('Other', 'Other')], max_length=50),
        ),
    ]
