# Generated by Django 5.2 on 2025-05-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_create_crop_classification_model'),
        ('core', '0015_remove_userprofile_theme_preference_and_more'),
    ]

    operations = [
        # This is a merge migration to reconcile parallel branches
        # Both parent migrations create the same CropClassification model
        # and try to remove the theme_preference field
    ]
