# Generated by Django 5.2 on 2025-05-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20250511_1742'),
    ]

    operations = [
        # This is a fake/empty migration to fix the database state
        # The theme_preference field and NotificationSettings model have already been removed
    ]
