# Generated by Django 5.2 on 2025-05-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_userprofile_theme_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='theme_preference',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
