# Generated by Django 5.2 on 2025-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_userprofile_theme_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='fertilizer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='fertilizer_type',
            field=models.CharField(blank=True, choices=[('Urea', 'Urea'), ('DAP', 'DAP'), ('NPK', 'NPK'), ('Organic', 'Organic'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='governorate',
            field=models.CharField(blank=True, choices=[('Ariana', 'Ariana'), ('Beja', 'Beja'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Gabes', 'Gabes'), ('Gafsa', 'Gafsa'), ('Jendouba', 'Jendouba'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kebili', 'Kebili'), ('Kef', 'Kef'), ('Mahdia', 'Mahdia'), ('Manouba', 'Manouba'), ('Medenine', 'Medenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Tunis', 'Tunis'), ('Zaghouan', 'Zaghouan')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='growing_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='harvest_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='pesticide_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='planting_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='rainfall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='soil_nitrogen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='soil_ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='soil_phosphorus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='soil_potassium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
