# Generated by Django 5.2 on 2025-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cropclassification_irrigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='antagonistic_plants',
            field=models.TextField(blank=True, help_text='Plants that should not be grown with this crop', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='companion_plants',
            field=models.TextField(blank=True, help_text='Plants that grow well with this crop', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='growth_days_max',
            field=models.IntegerField(blank=True, help_text='Maximum days to maturity', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='growth_days_min',
            field=models.IntegerField(blank=True, help_text='Minimum days to maturity', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_end_month',
            field=models.IntegerField(blank=True, help_text='Month index (0-11) when harvesting typically ends', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_start_month',
            field=models.IntegerField(blank=True, help_text='Month index (0-11) when harvesting typically begins', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_soil_temp',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum soil temperature for planting (°F)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional growing notes and tips', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='optimal_ph_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum optimal soil pH', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='optimal_ph_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum optimal soil pH', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_end_month',
            field=models.IntegerField(blank=True, help_text='Month index (0-11) when planting typically ends', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_start_month',
            field=models.IntegerField(blank=True, help_text='Month index (0-11) when planting typically begins', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='row_spacing',
            field=models.CharField(blank=True, help_text="Recommended row spacing (e.g., '30-36 inches')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='seed_depth',
            field=models.CharField(blank=True, help_text="Recommended planting depth (e.g., '1-2 inches')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sun_requirement',
            field=models.CharField(blank=True, help_text="Sun exposure needs (e.g., 'Full Sun')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='water_requirement',
            field=models.CharField(blank=True, choices=[('LOW', 'Low - Drought Tolerant'), ('MEDIUM', 'Medium - Average Water Needs'), ('HIGH', 'High - Requires Regular Watering'), ('VERY_HIGH', 'Very High - Requires Abundant Water')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='water_schedule',
            field=models.CharField(blank=True, help_text='Suggested watering frequency/schedule', max_length=100, null=True),
        ),
    ]
