# Generated by Django 5.2 on 2025-05-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farm_type', models.CharField(choices=[('CROP', 'Crop Farm'), ('LIVESTOCK', 'Livestock Farm'), ('DAIRY', 'Dairy Farm'), ('ORCHARD', 'Orchard'), ('VINEYARD', 'Vineyard'), ('MIXED', 'Mixed Use'), ('OTHER', 'Other')], default='CROP', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('size_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='core.userprofile')),
            ],
        ),
    ]
