# Generated by Django 5.2 on 2025-05-08 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_onboarding_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('notify_crop_health', models.BooleanField(default=True)),
                ('notify_pest_disease', models.BooleanField(default=True)),
                ('notify_satellite_imagery', models.BooleanField(default=False)),
                ('notify_weather_alerts', models.BooleanField(default=True)),
                ('notify_temperature_extremes', models.BooleanField(default=False)),
                ('notify_rainfall_forecasts', models.BooleanField(default=True)),
                ('notify_task_reminders', models.BooleanField(default=True)),
                ('notify_equipment_maintenance', models.BooleanField(default=True)),
                ('notify_planting_harvesting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.userprofile')),
            ],
        ),
    ]
