# Generated by Django 5.2 on 2025-05-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmcrop',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='farmcrop',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='farm_crop',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='farm_crop',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.DeleteModel(
            name='FarmCrop',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
