# Generated by Django 5.2 on 2025-05-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_farmcrop_crop_remove_farm_owner_and_more'),
    ]

    operations = [
    ]
